apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: flask-api-light
  name: flask-api-light
spec:
  containers:
  - image: hyukjun/flask-api-light:1.0
    name: flask-api-light
    ports:
    - containerPort: 5000
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: api-svc
spec:
  type: LoadBalancer
  selector:
    run: flask-api-light
  ports:
    - port: 80
      targetPort: 5000