apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: monitoring
spec:
  hard:
    requests.cpu: "3"
    requests.memory: "2Gi"
    limits.cpu: "4"
    limits.memory: "4Gi"