apiVersion: v1
kind: LimitRange
metadata:
  name: compute-resources
  namespace: monitoring
spec:
  limits:
  - default:
      cpu: "100m"       # Limit
      memory: "128Mi"   # Limit
    defaultRequest:
      cpu: "50m"       # Request
      memory: "64Mi"   # Request
    type: Container
