apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-app
  template:
    metadata:
      labels:
        app: db-app
    spec:
      containers:
      - name: db-app
        image: alpine
        command: ["/bin/sh"]
        args: ["-c", "echo DB Password is $DB_PASSWORD && sleep 3600"]
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: foo-secret
              key: db-password
