## External Ingress Controller Setting (AKS)

controller:
  ## Scaling
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 8
    targetCPUUtilizationPercentage: 50
    targetMemoryUtilizationPercentage: 50
  
  ## Preemption Priority Setting
  # priorityClassName: high-priority-nonpreempting

  ## Prometheus Monitoring (serviceMonitor - Diffrent Namespace)
  metrics:
    enabled: true
    # serviceMonitor:
    #   enabled: true
    #   additionalLabels:
    #     release: prometheus # Prometheus Release Name
  
  ## Azure LB Probe Setting
  service:
    annotations: 
      # externalTrafficPolicy: Local
      service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /healthz 
  
  ## Ingress Class
  electionID: external-ingress-controller-leader
  ingressClassResource:
    name: ingress-nginx-class
    enabled: true
    default: false
    controllerValue: "k8s.io/ingress-nginx"
  
  ## QoS: Burstable
  resources:
    limits:
      cpu: 1
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 256Mi