# AlertRule & RecordRule
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: prometheus-sample-record-rules
  # namespace: monitoring
  # labels:
  #   release: prometheus
spec:
  groups:
  - name: ./sample-record.rules
    rules:
    - record: code:prometheus_http_requests_total:sum
      expr: sum by (code) (prometheus_http_requests_total)