apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: test-pdb
spec:
  minAvailable: 4
  selector:
    matchLabels:
      app: test-pdb-nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-pdb-nginx
  name: test-pdb-nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      app: test-pdb-nginx
  template:
    metadata:
      labels:
        app: test-pdb-nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 64Mi
