apiVersion: apps/v1
kind: Deployment
metadata:
  name: applicaion-a
spec:
  selector:
    matchLabels:
      app: applicaion-a
  template:
    metadata:
      labels:
        app: applicaion-a
    spec:
      containers:
      - name: applicaion-a
        image: alpine
        resources:
          limits:
            memory: "32Mi"
            cpu: "10m"
        command: ["/bin/sh", "-c", "--"]
        args: ["while true; do wget -O- -q nginx-svc:8080; sleep 10s;done"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          limits:
            memory: "32Mi"
            cpu: "10m"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  selector:
    app: nginx
  ports:
  - port: 8080
    targetPort: 80



