apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mynginx
  template:
    metadata:
      labels:
        app: mynginx
    spec:
      containers:
      - name: mynginx
        image: nginx:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        volumeMounts:
          - name: myvol
            mountPath: /usr/share/nginx/html
      volumes:
        - name: myvol
          configMap: 
            name: nginx-index
---
apiVersion: v1
kind: Service
metadata:
  name: mynginx-clusterip
spec:
  selector:
    app: mynginx
  ports:
  - port: 8080
    targetPort: 80
