apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 10
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - aks-agentpool-17139092-vmss00000j
      containers:
      - name: myapp
        image: nginx
        resources:
          # Guaranteed
          limits:
            memory: "50Mi"
            cpu: "100m"
          requests:
            memory: "50Mi"
            cpu: "100m"
