apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: dev-slack-config
  namespace: monitoring
  labels:
    team: dev
spec:
  route:
    groupBy: ['namespace'] # 알람 그룹핑
    groupWait: 5s # 초기 알람 대기시간
    groupInterval: 10s
    repeatInterval: 1h
    receiver: 'slack-notification'  # receiver 이름
    continue: false
    # And 조건, 모든 matcher 일치 필요
    matchers:
      - matchType:  "="
        name: severity
        value: critical
  receivers:
  - name: 'slack-notification'  # receiver 이름
    slackConfigs:
    - channel: '#alert-test' # 슬랙 채널 이름
      sendResolved: true # 경고 해제 알림 전송
      # Secret 정보 입력, AlertmanagerConfig과 같은 네임스페이스에 있어야 함
      apiURL: 
        name: slack-bot-token-dev
        key: apiurl 
      httpConfig:
        authorization:
          type: Bearer 
          credentials: 
            name: slack-bot-token-dev
            key: token