# AlertRule & RecordRule
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  namespace: monitoring
  labels:
    prometheus: example
    release: prometheus # Prometheus.ruleSelector 와 일치 시켜야 함
  name: prometheus-example-rules
spec:
  groups:
  - name: ./example.rules
    rules:
    # 경고 테스트
    - alert: ExampleAlert
      expr: vector(1)

    # Pod 상태 실패 경고
    - alert: KubernetesPodNotHealthy
      expr: sum by (namespace, pod) (kube_pod_status_phase{phase=~"Pending|Unknown|Failed|Waiting"}) > 0
      for: 10s
      # Alertmanager.matchers 와 일치 시켜야 함 -> 경고 발송 채널 설정
      labels:
        custom: value
      annotations:
        summary: Kubernetes Pod not healthy (instance {{ $labels.instance }})
        description: "Pod {{ $labels.namespace }}/{{ $labels.pod }} has been in a non-running state for longer than 15 minutes.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"