loki:
  auth_enabled: false
  schemaConfig:
    configs:
      - from: 2024-04-01
        store: tsdb
        object_store: azure
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  ingester:
    chunk_encoding: snappy
  tracing:
    enabled: true
  querier:
    max_concurrent: 4

  storage:
    type: azure
    azure:
      # Name of the Azure Blob Storage account
      accountName: ""
      # Key associated with the Azure Blob Storage account
      accountKey: ""
      # Comprehensive connection string for Azure Blob Storage account (Can be used to replace endpoint, accountName, and accountKey)
      #connectionString: <your-connection-string>
      # Flag indicating whether to use Azure Managed Identity for authentication
      useManagedIdentity: false
      # Flag indicating whether to use a federated token for authentication
      useFederatedToken: false
      # Client ID of the user-assigned managed identity (if applicable)
      #userAssignedId: <your-user-assigned-id>
      # Timeout duration for requests made to the Azure Blob Storage account (in seconds)
      requestTimeout: 0
      # Domain suffix of the Azure Blob Storage service endpoint (e.g., core.windows.net)
      # endpointSuffix: 
    bucketNames:
      chunks: "chunks-test"
      ruler: "ruler-test"
      admin: "admin-test"
deploymentMode: SimpleScalable

backend:
  replicas: 2
  # Helm Package 삭제시 PVC도 함께 삭제
  persistence:
    enableStatefulSetAutoDeletePVC: true
  # Autoscaling
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 6
    targetCPUUtilizationPercentage: 60
read:
  replicas: 2
  persistence:
    enableStatefulSetAutoDeletePVC: true
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 6
    targetCPUUtilizationPercentage: 60
write:
  replicas: 2
  persistence:
    enableStatefulSetAutoDeletePVC: true
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 6
    targetCPUUtilizationPercentage: 60

# Disable chunkCache
chunksCache:
  enabled: false

# Disable minio storage
minio:
  enabled: false

# Zero out replica counts of other deployment modes
singleBinary:
  replicas: 0

ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0