loki: 
  auth_enabled: false 
 
  common: 
    path_prefix: /var/loki     
 
    ring: 
      kvstore: 
        store: memberlist 
 
  storage: 
    type: azure
 
  compactor: 
    working_directory: /var/loki/retention 
    shared_store: azure 
    retention_enabled: true   
 
  schema_config: 
    configs:   
      store: boltdb-shipper 
      object_store: azure 
      schema: v11 
      index: 
        prefix: loki_index_ 
        period: 24h 
 
 
  storage_config: 
    boltdb_shipper: 
      shared_store: azure 
      active_index_directory: /var/loki/index 
      cache_location: /var/loki/cache 
      cache_ttl: 24h 
 
    azure: 
      container_name: loki 
      account_name: ""
      use_managed_identity: false 
      account_key: ""
      request_timeout: 0       
 
    filesystem: 
      directory: /var/loki/chunks 
monitoring: 
  selfMonitoring: 
    grafanaAgent: 
      installOperator: false 