controller:
  replicas: 1
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
      ephemeral-storage: 1Gi
    requests:
      cpu: 50m
      memory: 64Mi
  metrics:
    enabled: true
  dashboard:
    enabled: true
    service:
      type: LoadBalancer