apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mynginx
  name: mynginx
spec:
  replicas: 5
  selector:
    matchLabels:
      app: mynginx
  template:
    metadata:
      labels:
        app: mynginx
    spec:
      containers:
      - image: nginx
        name: nginx
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 100m
            memory: 256Mi
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app: mynginx
        maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway # ScheduleAnyway, DoNotSchedule
      
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mynginx-pdb
spec:
  minAvailable: 4
  selector:
    matchLabels:
      app: mynginx