apiVersion: v1
data:
  proxy-connect-timeout: "10"
  proxy-read-timeout: "60"
  proxy-send-timeout: "60"
  use-forwarded-headers: "true"
  real-ip-header: "X-Forwarded-For"
  set-real-ip-from: "0.0.0.0/0"
  log-format: '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" $request_length $request_time [$proxy_upstream_name] [$proxy_alternative_upstream_name] $upstream_addr $upstream_response_length $upstream_response_time $upstream_status $req_id "$http_x_forwarded_for"'
  # allow-snippet-annotations: "true"
  # enable-modsecurity: "true"
kind: ConfigMap
metadata:
  name: ingress-nginx-ext-controller # Set <RELEASE_NAME>-controller
  namespace: ingress-nginx
