# External Ingress Controller in AKS
controller:
  service:
    annotations: 
      service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /healthz-custom
      prometheus.io/scrape: true
      prometheus.io/port: 10254
  electionID: external-ingress-controller-leader # 인그레스 컨트롤러의 상태 업데이트를 위함
  ingressClassResource: # 인그레스 클래스 세팅
    name: nginx-external
    enabled: true
    default: false
    controllerValue: "k8s.io/external-ingress-nginx"
  ingressClass: nginx-external # 하위버전의 호환성을 위한 세팅
  healthCheckPath: "/healthz"