apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  drink: {{ .Values.favorite.drink | repeat 5 | upper | quote }}
  food: {{ .Values.favorite.food | default "chiken" |quote }}