apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynginx
  labels:
    env: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mynginx
  template:
    metadata:
      labels:
        app: mynginx
    spec:
      # System 노드풀에 배치하기 위한 톨러레이션
      tolerations:
        - effect: NoSchedule
          key: CriticalAddonsOnly
          operator: "Exists"
      affinity:
        # System 노드풀에 배치
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.azure.com/mode
                  operator: "In"
                  values:
                    - "system"
        # AV Zone 으로 분산 처리
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: failure-domain.beta.kubernetes.io/zone
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - mynginx
      containers:
      - name: mynginx
        image: nginx:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80