apiVersion: v1
data:
  ## Connection 설정
  proxy-connect-timeout: "10"
  proxy-read-timeout: "60"
  proxy-send-timeout: "60"
  ## 로그 포맷
  log-format-upstream: 
    '$remote_addr - $remote_user [$time_local] "$request"
    $status $body_bytes_sent "$http_referer" "$http_user_agent"
    $request_length $request_time [$proxy_upstream_name] [$proxy_alternative_upstream_name] $upstream_addr
    $upstream_response_length $upstream_response_time $upstream_status $req_id
    "x_forwarded_for": "$proxy_add_x_forwarded_for"'
  ## 보안설정
  # allow-snippet-annotations: "true"
  # enable-modsecurity: "true"
kind: ConfigMap
metadata:
  name: ingress-nginx-ext-controller # Set <RELEASE_NAME>-controller
  namespace: ingress-nginx
