apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: istio-proxy
  namespace: istio-system
  labels:
    istio: proxy
spec:
  jobLabel: istio-proxy
  selector:
    matchLabels:
      security.istio.io/tlsMode: istio
  namespaceSelector:
    any: true
  podMetricsEndpoints:
    - portNumber: 15090 # Envoy Proxy의 메트릭 포트 (15090)
      path: /stats/prometheus # Prometheus 메트릭 경로
      interval: 15s # 수집 주기
      scrapeTimeout: 10s # 스크랩 타임아웃